# Header Menu
menu:
  Trang chủ: /
  Sản phẩm: /products/
  Dịch vụ: /services/
  Giới thiệu: /about/
  Liên hệ: /contact/
  Blog: /archives/ # can set archive-dir in root config to custom value
   
rss: /atom.xml

# Content
excerpt_link: Xem thêm
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
  twitter: https://twitter.com/suakhoabmt
  facebook: https://www.facebook.com/suakhoabmt
  rss: atom.xml

# Miscellaneous
color_scheme: blue   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: suakhoabmt # twitter username without the @
default_author: Anonymous

about: Mở & làm chìa khóa, làm remote cửa cuốn, xe hơi. Cung cấp khóa, chìa khóa và các vật tư ngành khóa.
phone: (+84)942.97.59.59
email: trtienlee@gmail.com
address_1: 10 Nguyễn Chí Thanh
address_2: Thành Phố Buôn Ma Thuột
address_3: Tỉnh Đăk Lăk, Việt Nam
skype: trtienlee
facebook: trtienlee
zalo: 0942975959
lat: 12.693081 
long: 108.064679
